Add change font button to board formspec
mt-mods/display_modpack pull request #5
Opened 2023-09-09 09:11 UTC by Niklp09

Closes https://github.com/mt-mods/display_modpack/issues/4

2023-09-09 12:23 UTC, OgelGames commented
IMO the wipe button should be replaced with the font button.

Also, I noticed the text and buttons are a bit too far down. Would be good to fix that.

![image](https://github.com/mt-mods/display_modpack/assets/48543043/2081b0b5-e1f2-446d-8a15-d495c44b91e8)

2023-09-13 04:49 UTC, OgelGames requested changes

2023-09-13 04:49 UTC, OgelGames commented on boards/init.lua
> +		"button[3,3.35;2,1;font;"..FS("Font").."]")
```suggestion
		"button_exit[1,2.75;2,1;ok;"..FS("Write").."]"..
		"button[3,2.75;2,1;font;"..FS("Font").."]")
```

2023-09-13 04:49 UTC, OgelGames commented on boards/init.lua
>  		"textarea[0.5,0.7;5.5,3;display_text;"..FS("Text")..";" .. display_text .. "]"..
```suggestion
		"size[6,3.5]"..default.gui_bg..default.gui_bg_img..default.gui_slots..
		"textarea[0.55,0.25;5.5,3;display_text;"..FS("Text")..";" .. display_text .. "]"..
```

2023-09-13 04:50 UTC, OgelGames commented
Suggested changes to fix the position of the text area.

Looks like this now: 
![image](https://github.com/mt-mods/display_modpack/assets/48543043/c0697a16-67e7-47eb-b79a-5e462fe6ff9c)

2023-09-13 12:36 UTC, Niklp09 commented
The formspec look currently like this. Better IMO
![image](https://github.com/mt-mods/display_modpack/assets/89982526/83eff35e-2887-4d02-9141-33031a552ea1)

2023-09-13 13:45 UTC, merged